version: "3"
services:
  javavulnlab:
    build:
      context: .
      args:
        SHIFTLEFT_ORG_ID: "${ORG}"
        SHIFTLEFT_ACCESS_TOKEN: "${TOKEN}"
    ports:
      - 8080:8080
    links:
      - mysql
    environment:
      - SHIFTLEFT_SEC_MODE=REPORT
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
