on: push

name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Docker build
        env:
          SHIFTLEFT_ORG_ID: ${{ secrets.SHIFTLEFT_ORG }}
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        run: "docker build --build-arg SHIFTLEFT_ORG=$SHIFTLEFT_ORG_ID --build-arg SHIFTLEFT_ACCESS_TOKEN=$SHIFTLEFT_ACCESS_TOKEN -t preetamjinka/javavulnerablelab:latest ."
